### ISSUE TITLE
При пополнении счета, итогом в балансе отображается сумма, на которую пополняли.

### ISSUE THREAD

**Issue by PotapovEvgeny** [KindCoffeeBear/javaqa-team-diplom-2#10]
#**Описание**
При пополнении balance на сумму amount , в балансе отображается количество, на которое было пополнение, а не общая сумма.

#**Локация дефекта**

  https://github.com/KindCoffeeBear/javaqa-team-diplom-2/blob/0943da73b0a0473d336a0c349813251f86cba4ba/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68

#**Шаги воспроизведения**
Открыть [проект Maven](https://github.com/KindCoffeeBear/javaqa-team-diplom-2) в IDEA
Создать тестовый класс объекта.
Создать тест на метод add.
Выставить значение переменной balance 2_000 и значение переменной amount 3_000.
Запустить тест.
Посмотреть на вывод в консоли
Ожидаемый результат: Вывод итоговой суммы 5_000.
Фактический результат: Вывод итоговой суммы 3_000.

#**Тест** 
https://github.com/KindCoffeeBear/javaqa-team-diplom-2/blob/0943da73b0a0473d336a0c349813251f86cba4ba/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L9

#**Скриншот**
![Screenshot_1](https://github.com/KindCoffeeBear/javaqa-team-diplom-2/assets/147318052/46dd6495-e6f5-42fa-bd1a-e196e5f4a748)

#**Окружение**
Операционная система: Windows 10 PRO 22H2
IDE: Intelij IDEA 2023.2.4 (Community Edition)
Java: OpenJDK 11
@KindCoffeeBear

**Comment by KindCoffeeBear** [comment]
Исправлено
