### ISSUE TITLE
Не выдает исключение вида IllegalArgumentException при создании нового объекта сберегательного счета с минимальным балансом больше максимального.

### ISSUE THREAD

**Issue by PotapovEvgeny** [KindCoffeeBear/javaqa-team-diplom-2#11]
**Описание**

При создании нового объекта сберегательного счета SavingAccount , где minBalance > maxBalance, должно выкидываться исключение вида IllegalArgumentException.

**Локация дефекта**

https://github.com/KindCoffeeBear/javaqa-team-diplom-2/blob/6250f38c1770e0be44ce7300ad3d5d59df98a7cb/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

**Шаги воспроизведения**

1.Открыть [проект Maven](https://github.com/KindCoffeeBear/javaqa-team-diplom-2) в IDEA
2.Создать тест в классе **_SavingAccountTest_** на метод _**SavingAccount**_ с параметрами:
                            **_initialBalance_ = 2_000;
                           _minBalance_ = 20_000;
                           _maxBalance_ = 10_000;
                           _rate_ = 5.**
3.Выполнить операцию при введенной величине minBalance большей, чем maxBalance.
4.Посмотреть на вывод в консоли.

Ожидаемый результат: Вывод сообщения: "Минимальный баланс не может быть больше максимального".
Фактический результат: Не выдает исключение.

**Тест**
 https://github.com/KindCoffeeBear/javaqa-team-diplom-2/blob/0943da73b0a0473d336a0c349813251f86cba4ba/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L23

**Скриншот**
![Screenshot_2](https://github.com/KindCoffeeBear/javaqa-team-diplom-2/assets/147318052/7af275e5-f49a-4d7b-8118-56c1f0756d39)

**Окружение**
Операционная система: Windows 10 PRO 22H2
IDE: Intelij IDEA 2023.2.4 (Community Edition)
Java: OpenJDK 11
@KindCoffeeBear

**Comment by KindCoffeeBear** [comment]
Исправлено
