### ISSUE TITLE
Не выдает исключение вида IllegalArgumentException при создании нового объекта сберегательного счета с начальным балансом меньше минимального.

### ISSUE THREAD

**Issue by PotapovEvgeny** [KindCoffeeBear/javaqa-team-diplom-2#12]
**Описание**

При создании нового объекта сберегательного счета SavingAccount , где initialBalance < minBalance, должно выкидываться исключение вида IllegalArgumentException.

**Локация дефекта**

https://github.com/KindCoffeeBear/javaqa-team-diplom-2/blob/6250f38c1770e0be44ce7300ad3d5d59df98a7cb/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

**Шаги воспроизведения**

1.Открыть [проект Maven](https://github.com/KindCoffeeBear/javaqa-team-diplom-2) в IDEA
2.Создать тест в классе SavingAccountTest на метод SavingAccount с параметрами:
initialBalance = 2_000;
minBalance = 3_000;
maxBalance = 10_000;
rate = 5.
3.Выполнить операцию при введенной величине initialBalance меньшей, чем minBalance.
4.Посмотреть на вывод в консоли.

Ожидаемый результат: Вывод сообщения: "Начальный баланс не может быть меньше минимального".
Фактический результат: Не выдает исключение..

**Тест**

 https://github.com/KindCoffeeBear/javaqa-team-diplom-2/blob/0943da73b0a0473d336a0c349813251f86cba4ba/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L45

**Скриншот**

![Screenshot_3](https://github.com/KindCoffeeBear/javaqa-team-diplom-2/assets/147318052/4fbb9947-4605-4511-b1f9-fd7b4849e33e)

**Окружение**
Операционная система: Windows 10 PRO 22H2
IDE: Intelij IDEA 2023.2.4 (Community Edition)
Java: OpenJDK 11
@KindCoffeeBear

**Comment by KindCoffeeBear** [comment]
Исправлено
