### ISSUE TITLE
Не выдает исключение вида IllegalArgumentException при создании нового объекта сберегательного счета с отрицательным минимальным балансом.

### ISSUE THREAD

**Issue by PotapovEvgeny** [KindCoffeeBear/javaqa-team-diplom-2#14]
**Описание**

При создании нового объекта сберегательного счета SavingAccount , где minBalance < 0, должно выкидываться исключение вида IllegalArgumentException.

**Локация дефекта**
https://github.com/KindCoffeeBear/javaqa-team-diplom-2/blob/6250f38c1770e0be44ce7300ad3d5d59df98a7cb/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

**Шаги воспроизведения**

1.Открыть [проект Maven](https://github.com/KindCoffeeBear/javaqa-team-diplom-2) в IDEA
2.Создать тест в классе SavingAccountTest на метод SavingAccount с параметрами:
initialBalance = 2_000;
minBalance = -1_000;
maxBalance = 10_000;
rate = 5.
3.Выполнить операцию при введенной отрицательной величине minBalance.
4.Посмотреть на вывод в консоли.

Ожидаемый результат: Вывод сообщения: "Минимальный баланс не может быть отрицательным".
Фактический результат: Не выдает исключение.

**Тест**
https://github.com/KindCoffeeBear/javaqa-team-diplom-2/blob/0943da73b0a0473d336a0c349813251f86cba4ba/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L66-L75

**Скриншот**

![Screenshot_5](https://github.com/KindCoffeeBear/javaqa-team-diplom-2/assets/147318052/51eabbd4-8215-4877-998e-25b6836cc2d0)

**Окружение**
Операционная система: Windows 10 PRO 22H2
IDE: Intelij IDEA 2023.2.4 (Community Edition)
Java: OpenJDK 11
@KindCoffeeBear

**Comment by KindCoffeeBear** [comment]
Исправлено
