### ISSUE TITLE
Не корректно рассчитывается новый баланс при пополнении счета на положительное число рублей во время обращения к методу add.

### ISSUE THREAD

**Issue by PotapovEvgeny** [KindCoffeeBear/javaqa-team-diplom-2#15]
**Описание**

При создании нового объекта сберегательного счета SavingAccount и обращении к методу add значение нового баланса должно быть получено путем сложения initialBalance (текущий баланс) и amount (сумма пополнения).

**Локация дефекта**

https://github.com/KindCoffeeBear/javaqa-team-diplom-2/blob/6250f38c1770e0be44ce7300ad3d5d59df98a7cb/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L73

**Шаги воспроизведения**

1.Открыть [код программы](https://github.com/ValeryGil/javaqa-team-diplom-2/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA.
2.Создать тест в классе SavingAccountTest на метод add с параметрами:
initialBalance = 2_000;
minBalance = 1_000;
maxBalance = 10_000;
rate = 5.
3.Обратиться к методу add с параметром:
amount = 1_000.
4.Выполнить операцию пополнения счета на величину amount (шаг 3).
5.Посмотреть на вывод в консоли.

Ожидаемый результат: 3_000.
Фактический результат: 1_000.

**Тест**

https://github.com/KindCoffeeBear/javaqa-team-diplom-2/blob/0943da73b0a0473d336a0c349813251f86cba4ba/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L241-L255

**Скриншот**

![Screenshot_6](https://github.com/KindCoffeeBear/javaqa-team-diplom-2/assets/147318052/eed81df6-1591-45a5-884c-e89eead39c3d)

Окружение
Операционная система: Windows 10 PRO 22H2
IDE: Intelij IDEA 2023.2.4 (Community Edition)
Java: OpenJDK 11
@KindCoffeeBear

**Comment by KindCoffeeBear** [comment]
Исправлено
