### ISSUE TITLE
Сумма процентов по сберегательной карте при положительном балансе равна 0.

### ISSUE THREAD

**Issue by PotapovEvgeny** [KindCoffeeBear/javaqa-team-diplom-2#16]
**Описание**
Если баланс положительный, то сумма процентов равна 0.

**Локация дефекта**
https://github.com/KindCoffeeBear/javaqa-team-diplom-2/blob/ed0e8c476dd33600561f7a909ad6f2ad6a093f59/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L113

**Шаги воспроизведения**
1. Открыть [проект Maven](https://github.com/KindCoffeeBear/javaqa-team-diplom-2) в IDEA
2. Создать объект класса SavingAccount со значениями начального баланса initialBalance 50, minBalance 0, maxBalance 10_000 и ставки rate 5
3. Рассчитать сумму процентов (метод yearChange) по сберегательной карте

_Ожидаемый результат_: Сумма процентов равна 2
_Фактический результат_: Сумма процентов равна 0

**Тест**
https://github.com/KindCoffeeBear/javaqa-team-diplom-2/blob/17472654811a49da809892196594df99a292b935/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L285-L298

**Скриншот**

![Screenshot_12](https://github.com/KindCoffeeBear/javaqa-team-diplom-2/assets/147318052/2fe791f0-ccf9-4a52-8d1b-db136c9a9c75)

**Окружение**
Операционная система: Windows 10 PRO 22H2
IDE: Intelij IDEA 2023.2.4 (Community Edition)
Java: OpenJDK 11
@KindCoffeeBear

**Comment by KindCoffeeBear** [comment]
Исправлено
