### ISSUE TITLE
При покупке на положительное число рублей возвращается "ложь" при значении нового баланса равном значению минимального во время обращения к методу pay.

### ISSUE THREAD

**Issue by PotapovEvgeny** [KindCoffeeBear/javaqa-team-diplom-2#17]
**Описание**
При создании нового объекта сберегательного счета SavingAccount и обращении к методу pay должно возвращаться значение true , если balance уменьшился до величины равной значению minBalance.

**Локация дефекта**
https://github.com/KindCoffeeBear/javaqa-team-diplom-2/blob/ed0e8c476dd33600561f7a909ad6f2ad6a093f59/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L71

**Шаги воспроизведения**

1.Открыть [проект Maven](https://github.com/KindCoffeeBear/javaqa-team-diplom-2) в IDEA

2.Создать объект класса SavingAccount со значениями начального баланса 
initialBalance 5_000, 
minBalance 1_000, 
maxBalance 10_000 
rate 5
3.Обратиться к методу pay с параметром:
amount = 4_000.
4.Выполнить операцию покупки на величину amount = 4_000 таким образом, чтобы получившееся значение initialBalance оказалась равном значению minBalance.
5.Посмотреть на вывод в консоли.

_Ожидаемый результат_: true.
_Фактический результат_: false.

**Тест**
https://github.com/KindCoffeeBear/javaqa-team-diplom-2/blob/ed0e8c476dd33600561f7a909ad6f2ad6a093f59/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L300-L312

**Скриншот**
![Screenshot_8](https://github.com/KindCoffeeBear/javaqa-team-diplom-2/assets/147318052/9b432f57-5d15-44d4-bf01-b0c4446a9c19)

**Окружение**
Операционная система: Windows 10 PRO 22H2
IDE: Intelij IDEA 2023.2.4 (Community Edition)
Java: OpenJDK 11
@KindCoffeeBear

**Comment by KindCoffeeBear** [comment]
Исправлено
