### ISSUE TITLE
При пополнении на положительное число рублей возвращается "ложь" при значении нового баланса равном значению максимального во время обращения к методу add.

### ISSUE THREAD

**Issue by PotapovEvgeny** [KindCoffeeBear/javaqa-team-diplom-2#18]
**Описание**
При создании нового объекта сберегательного счета SavingAccount и обращении к методу add должно возвращаться значение true , если balance увеличился до величины равной значению maxBalance.

**Локация дефекта**
https://github.com/KindCoffeeBear/javaqa-team-diplom-2/blob/ed0e8c476dd33600561f7a909ad6f2ad6a093f59/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L95

**Шаги воспроизведения**

1.Открыть [проект Maven](https://github.com/KindCoffeeBear/javaqa-team-diplom-2) в IDEA
2.Создать тест в классе SavingAccountTest на метод add с параметрами:
initialBalance = 50_000;
minBalance = 10_000;
maxBalance = 100_000;
rate = 5.
3.Обратиться к методу add с параметром:
amount = 50_000.
4.Выполнить операцию пополнения счета на величину amount = 50_000 таким образом, чтобы получившееся значение initialBalance оказалась равном значению maxBalance.
5.Посмотреть на вывод в консоли.

_Ожидаемый результат_: true.
_Фактический результат_: false.

**Тест**
https://github.com/KindCoffeeBear/javaqa-team-diplom-2/blob/ed0e8c476dd33600561f7a909ad6f2ad6a093f59/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L330-L342

**Скриншот**
![Screenshot_9](https://github.com/KindCoffeeBear/javaqa-team-diplom-2/assets/147318052/f59efd3c-4693-4472-a816-cea4b672751c)

**Окружение**
Операционная система: Windows 10 PRO 22H2
IDE: Intelij IDEA 2023.2.4 (Community Edition)
Java: OpenJDK 11
@KindCoffeeBear

**Comment by KindCoffeeBear** [comment]
Исправлено
