### ISSUE TITLE
При пополнении сберегательного счета на сумму равной initialBalance, во время обращения к методу add, значение нового баланса не равно значению maxBalance.

### ISSUE THREAD

**Issue by PotapovEvgeny** [KindCoffeeBear/javaqa-team-diplom-2#19]
**Описание**
При пополнении баланса сберегательного счета, новый баланс отображается не корректно.

**Локация дефекта**
https://github.com/KindCoffeeBear/javaqa-team-diplom-2/blob/ed0e8c476dd33600561f7a909ad6f2ad6a093f59/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L95

**Шаги воспроизведения**
1.Открыть [проект Maven](https://github.com/KindCoffeeBear/javaqa-team-diplom-2) в IDEA
2.Создать тест в классе SavingAccountTest на метод add с параметрами:
initialBalance = 50_000;
minBalance = 10_000;
maxBalance = 100_000;
rate = 5.
3..Обратиться к методу add с параметром:
amount = 50_000.

4.Запустить тест.
5.Посмотреть на вывод в консоли

_Ожидаемый результат_:100_000.
_Фактический результат_:  50_000.

**Тест**
https://github.com/KindCoffeeBear/javaqa-team-diplom-2/blob/ed0e8c476dd33600561f7a909ad6f2ad6a093f59/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L344-L358

**Скриншот**

![Screenshot_10](https://github.com/KindCoffeeBear/javaqa-team-diplom-2/assets/147318052/4f7712a8-3282-4739-a9ea-5f7442e04919)

**Окружение**
Операционная система: Windows 10 PRO 22H2
IDE: Intelij IDEA 2023.2.4 (Community Edition)
Java: OpenJDK 11
@KindCoffeeBear

**Comment by KindCoffeeBear** [comment]
Исправлено
