### ISSUE TITLE
Некорректное обновление баланса методом pay класса SavingAccount

### ISSUE THREAD

**Issue by PotapovEvgeny** [KindCoffeeBear/javaqa-team-diplom-2#20]
**Описание**
Сумма покупки amount может превышать остаток денежных средств на счёте minBalance, что противоречит техническому заданию

**Локация дефекта**
https://github.com/KindCoffeeBear/javaqa-team-diplom-2/blob/79c5d07819e010ee79742cc261fc47d63e9be59f/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L69

**Шаги воспроизведения**
1.Открыть [проект Maven](https://github.com/KindCoffeeBear/javaqa-team-diplom-2) в IDEA
2.Создать тест в классе SavingAccountTest на метод pay с параметрами:
initialBalance = 50_000;
minBalance = 10_000;
maxBalance = 100_000;
rate = 5.
3..Обратиться к методу pay с параметром:
amount = 45_000.

4.Запустить тест.
5.Посмотреть на вывод в консоли

Ожидаемый результат:50_000.
Фактический результат: 5_000.

**Тест**

https://github.com/KindCoffeeBear/javaqa-team-diplom-2/blob/1117e5e4704f25d867215264bdf35304417698f4/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L360-L374

**Скриншот**

![Screenshot_13](https://github.com/KindCoffeeBear/javaqa-team-diplom-2/assets/147318052/f5c0cbfb-ac82-4744-af2d-4c22d486f637)

**Окружение**
Операционная система: Windows 10 PRO 22H2
IDE: Intelij IDEA 2023.2.4 (Community Edition)
Java: OpenJDK 11
@KindCoffeeBear

**Comment by KindCoffeeBear** [comment]
Исправлено
